<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="FREE CRM Application Test Automation Test Suite" duration-ms="16487" started-at="2018-03-06T12:19:12Z" finished-at="2018-03-06T12:19:29Z">
    <groups>
    </groups>
    <test name="Free CRM App Test Cases" duration-ms="16487" started-at="2018-03-06T12:19:12Z" finished-at="2018-03-06T12:19:29Z">
      <class name="shubham.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:shubham.LoginPageTest@61832929]" name="setUp" is-config="true" duration-ms="4807" started-at="2018-03-06T17:49:12Z" finished-at="2018-03-06T17:49:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="checkURL()[pri:0, instance:shubham.LoginPageTest@61832929]" name="checkURL" duration-ms="13" started-at="2018-03-06T17:49:17Z" finished-at="2018-03-06T17:49:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkURL -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:shubham.LoginPageTest@61832929]" name="tearDown" is-config="true" duration-ms="84" started-at="2018-03-06T17:49:17Z" finished-at="2018-03-06T17:49:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:shubham.LoginPageTest@61832929]" name="setUp" is-config="true" duration-ms="3421" started-at="2018-03-06T17:49:17Z" finished-at="2018-03-06T17:49:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="login()[pri:0, instance:shubham.LoginPageTest@61832929]" name="login" duration-ms="8020" started-at="2018-03-06T17:49:20Z" finished-at="2018-03-06T17:49:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://qawindows.veraqa.com/dashboard] but found [https://qawindows.veraqa.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://qawindows.veraqa.com/dashboard] but found [https://qawindows.veraqa.com/login]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at shubham.LoginPageTest.login(LoginPageTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:shubham.LoginPageTest@61832929]" name="tearDown" is-config="true" duration-ms="128" started-at="2018-03-06T17:49:28Z" finished-at="2018-03-06T17:49:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- shubham.LoginPageTest -->
    </test> <!-- Free CRM App Test Cases -->
  </suite> <!-- FREE CRM Application Test Automation Test Suite -->
</testng-results>
